
![image](https://static001.geekbang.org/resource/image/47/93/47c8429fc30aec201286b47f3c1a5993.png)

异常分为可处理的（Error） 和不可处理的（Exception）

##  Java程序捕获异常

1. 在编译生成的字节码中，每个方法都附带一个异常表  
2. 由 from 指针、to 指针、target 指针以及所捕获的异常类型构成  

```

public static void main(String[] args) {
  try {
    mayThrowException();
  } catch (Exception e) {
    e.printStackTrace();
  }
}
// 对应的 Java 字节码
public static void main(java.lang.String[]);
  Code:
    0: invokestatic mayThrowException:()V
    3: goto 11
    6: astore_1
    7: aload_1
    8: invokevirtual java.lang.Exception.printStackTrace
   11: return
  Exception table:
    from  to target type
      0   3   6  Class java/lang/Exception  // 异常表条目


```

3. 当程序触发异常时，Java 虚拟机会从上至下遍历异常表中的所有条目  
4. 如果匹配不到异常，则会弹出当前方法对应的 Java 栈帧，并且在调用者（caller)中匹配异常  

![image](https://static001.geekbang.org/resource/image/17/06/17e2a3053b06b0a4383884f106e31c06.png)  

5. 如果finally代码块里也触发了异常，那么虚拟机会抛出finally里的异常  

##  "Supressed"异常

try-with-resources
* 自动关闭实现AutoCloseable的类   
* 还会使用 Supressed异常的功能，来避免原异常“被消失”
